### ISSUE TITLE
Alternative to forcing ro.product.device as tissot_sprout 

### ISSUE THREAD

**Issue by danielstuart14** [Magisk-Modules-Repo/Xiaomi-Mi-A1-Stock-Camera#2]
Hi, that's a really nice module!
I'd recommend you avoid changing read-only properties.

After checking the camera smali code with IDA, I may have a solution (I didn't test it yet):
1. Extract the file "classes.dex" from the apk (with winrar)
2. Change these bytes: ```6E 20 7C 33 20 00 0A 00 6A 00 D2 04 1B 00 72 44```   to: ```6E 20 7C 33 00 00 0A 00 6A 00 D2 04 1B 00 72 44``` (with hexEdit)
4. Replace the original file with the modded one inside the apk

You still need to add a device feature config with the device name, but you can do that with a magisk script. (I'm trying to find a way to force it to use tissot_sprout.xml by default)

What it does: 
First patch: It bypasses the product check for tissot.
Before:
![before](https://i.imgur.com/QiZK9h3.png)

After:
![After](https://i.imgur.com/g1h4VH5.png)

**Comment by joeyhuab** [comment]
Thanks for this! I will try it out and comment back if it works properly. :)

**Comment by joeyhuab** [comment]
App wouldn't open :( Nor wouldn't install normally.
